"use client";

/**
 * FlowIconKey → Phosphor component. Lives outside Flow.tsx so the mobile
 * stepper and any future consumer share one registry, and so Flow.tsx stays
 * about geometry and state rather than a wall of imports. Keys are the only
 * thing content files know — components never cross the server boundary.
 */

import type { Icon } from "@phosphor-icons/react";
import {
  ArrowsClockwise,
  Bell,
  BookOpen,
  Buildings,
  Calculator,
  CalendarCheck,
  ChartBar,
  ChatCircle,
  CheckCircle,
  ClockCounterClockwise,
  CreditCard,
  Database,
  DownloadSimple,
  EnvelopeSimple,
  FileText,
  ForkKnife,
  GearSix,
  Globe,
  Lightbulb,
  Magnet,
  MagnifyingGlass,
  MapPin,
  Megaphone,
  Note,
  Phone,
  PhoneX,
  Pill,
  Pulse,
  Receipt,
  RocketLaunch,
  ShoppingCart,
  Sparkle,
  Star,
  Stethoscope,
  Table,
  Tag,
  Trophy,
  User,
  UserMinus,
  UserPlus,
  UsersThree,
} from "@phosphor-icons/react/dist/ssr";
import type { FlowIconKey } from "@/lib/flow";

export const FLOW_ICONS: Record<FlowIconKey, Icon> = {
  lead: UserPlus,
  ai: Sparkle,
  crm: Database,
  email: EnvelopeSimple,
  calendar: CalendarCheck,
  user: User,
  users: UsersThree,
  globe: Globe,
  chart: ChartBar,
  phone: Phone,
  "phone-x": PhoneX,
  note: Note,
  file: FileText,
  table: Table,
  clock: ClockCounterClockwise,
  "user-minus": UserMinus,
  card: CreditCard,
  receipt: Receipt,
  cart: ShoppingCart,
  star: Star,
  check: CheckCircle,
  bell: Bell,
  chat: ChatCircle,
  magnet: Magnet,
  search: MagnifyingGlass,
  mappin: MapPin,
  buildings: Buildings,
  rocket: RocketLaunch,
  repeat: ArrowsClockwise,
  megaphone: Megaphone,
  tag: Tag,
  book: BookOpen,
  download: DownloadSimple,
  trophy: Trophy,
  lightbulb: Lightbulb,
  pulse: Pulse,
  calculator: Calculator,
  gear: GearSix,
  fork: ForkKnife,
  stethoscope: Stethoscope,
  pill: Pill,
};
